### ISSUE TITLE
Audit lokacore

### ISSUE THREAD

**Issue by Lokathor** [rust-secure-code/safety-dance#14]
Some sort of _crazy idiot_ is claiming to have (trait bound) safe casting utilities for all sorts of stuff in their crate. Surely this is too good to be true, they must have screwed up somewhere.

<https://github.com/Lokathor/lokacore>

**Comment by Shnatsel** [comment]
https://crates.io/crates/lokacore has at about 1 download per day on crates.io. Could be too small fish to fry.

**Comment by Lokathor** [comment]
<3

but verified safe casting is a public good, and if we can convert people to using that instead of transmute all over the place that's a safety gain that can grow quite a bit over time

**Comment by Shnatsel** [comment]
I believe the safe type conversions have been split into a separate crate: https://crates.io/crates/bytemuck

This could come in handy as a safe abstraction, so auditing this is probably worthwhile.

**Comment by Lokathor** [comment]
Closing in favor of https://github.com/rust-secure-code/safety-dance/issues/43
