### ISSUE TITLE
Audit spin

### ISSUE THREAD

**Issue by Shnatsel** [rust-secure-code/safety-dance#18]
`spin` crate provides `no_std` spinlocks. It has 6000 downloads/day on crates.io and is a transitive dependency of `lazy_static!` in `no_std` mode.

**Comment by Shnatsel** [comment]
@64 has audited the RwLock implementation and discovered issues: https://github.com/mvdnes/spin-rs/issues/65
This is now a RustSec advisory: https://github.com/RustSec/advisory-db/pull/132

They have also rewritten it based on Folly to fix those issues: https://github.com/mvdnes/spin-rs/pull/66 
The new implementation has been reviewed by @xacrimon.

**Comment by 64** [comment]
FWIW, I had a quick look over the other parts of spin and didn't see any glaring issues. If someone is going to take a proper look I'd recommend auditing `Once` because that's what lazy_static uses.

**Comment by Shnatsel** [comment]
Conversion of `Once` to `MaybeUninit<T>` is outstanding: https://github.com/mvdnes/spin-rs/pull/68

The rest of Once could still use a soundness audit.

**Comment by xacrimon** [comment]
I've looked through and tested `Once` as rigourusly as my knowledge allows and I have found no issues.

**Comment by Shnatsel** [comment]
Great! If the code isn't extensively commented already, it would be nice to add comments in the form of "This is sound because..."
