### ISSUE TITLE
Audit bytemuck

### ISSUE THREAD

**Issue by Lokathor** [rust-secure-code/safety-dance#43]
https://crates.io/crates/bytemuck

The 0.1 is released, there's a 0.1.1-alpha sitting in git that doesn't have any particular changes in it at the moment.

**Comment by Shnatsel** [comment]
Not a great deal of dependents so far, but could be useful as a safe abstraction for other crates. I've been dissatisfied with `safe_transmute` but this looks much more promising.

**Comment by Shnatsel** [comment]
Bytemuck has seen independent soundness audit via cargo-crev (e.g. https://github.com/HeroicKatora/crev-proofs/commit/17f1e67dd95e5e527605864fe842cc1f42af4a4b). Being a safe abstraction over an inherently unsafe operation, there's not much room for reducing usage of unsafe code. Closing.
